<div class="float-left mr-4">
    <a class="btn btn-primary" href="?f=menu&m=insert" role="button">TAMBAH DATA</a>
</div>
<h3>Menu</h3>

<?php 
    if (isset($_POST['opsi'])) {
        $opsi = $_POST['opsi'];

        $where = "WHERE idkategori= $opsi";

        //echo $where;
    }else{
        $opsi = 0;
        $where = "";
    }
?>

<div class="mt-4 mb-4">
    <?php 
        $rowkategori = $db->getAll("SELECT * FROM tblkategori ORDER BY kategori ASC");
    ?>

    <form action="" method="post">
        <select name="opsi" onchange="this.form.submit()">
            <?php foreach($rowkategori as $r): ?>
                <option 
                    <?php if(isset($opsi) && $r['idkategori']==$opsi) echo "selected"; ?>
                    value="<?= $r['idkategori'] ?>">
                    <?= $r['kategori'] ?>
                </option>
            <?php endforeach ?>
        </select>
    </form>
</div>

<?php 
    $jumlahdata = $db->rowCOUNT("SELECT idmenu FROM tblmenu $where");
    $banyak = 3;

    $halaman = ceil($jumlahdata / $banyak);

    if (isset($_GET['p'])) {
        $p = $_GET['p'];
        $mulai = ($p * $banyak) - $banyak;
    } else {
        $p = 1;
        $mulai = 0;
    }

    $sql = "SELECT * FROM tblmenu $where ORDER BY menu ASC LIMIT $mulai,$banyak";
    $row = $db->getAll($sql);

    $no = 1 + $mulai;
?>

<table class="table table-bordered w-80">
    <thead>
        <tr>
            <th>No</th>
            <th>Menu</th>
            <th>Harga</th>
            <th>Gambar</th>
            <th>Delete</th>
            <th>Update</th>
        </tr>
    </thead>
    <tbody>
        <?php if(!empty($row)) { ?>
        <?php foreach($row as $r): ?>
        <tr>
            <td><?= $no++ ?></td>
            <td><?= $r['menu'] ?></td>
            <td><?= $r['harga'] ?></td>
            <td><img style="width:150px;" src="../Upload/<?= $r['gambar'] ?>" alt=""></td>
            <td><a href="?f=menu&m=delete&id=<?= $r['idmenu'] ?>">Delete</a></td>
            <td><a href="?f=menu&m=update&id=<?= $r['idmenu'] ?>">Update</a></td>
        </tr>
        <?php endforeach; ?>
        <?php } ?>
    </tbody>
</table>

<?php 
    for ($i=1; $i <= $halaman ; $i++) { 
        echo '<a href="?f=menu&m=select&p='.$i.'">'.$i.'</a>';
        echo '&nbsp;&nbsp;&nbsp;';
    }
?>

